# Generated by Django — creates the first "violations_violation" database table.
# You usually do NOT edit migration files by hand.
# To change the table later: edit models.py, then run:
#   python manage.py makemigrations
#   python manage.py migrate

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_id', models.CharField(help_text='Unique ID from the source dataset (or a local key).', max_length=64, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('borough', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='Open', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
